from pymongo import MongoClient
client = MongoClient('localhost', 27017)
db = client.dbsparta

doc = [
   {

      "id": 1,
      "name": "서울만남의광장휴게소(부산방향)",
      "image": "https://me2.kr/utu91",
      "url": "https://goo.gl/maps/cbfS9oFhpNR43ebK7",
      "address": "서울 서초구 양재대로12길 73-71",
      "number": "02-578-3372",
      "menu": "말죽거리소고기국밥",
      "menu_image": "https://me2.kr/9mh1v",
      "price": "7,000",
      "score": "3.7 ★★★★☆",
      "lat": "37.46008802",
      "lng": "127.0419423",
      "menu_info": "든든한 말죽거리 소고기국밥! 직접 우려낸 사골육수를 사용해 정성을 다해 만들어 한 숟가락 국물을 떠먹는 순간 속이 든든해지는 환상의 국밥을 몸으로 느낄 수 있다!",
      "like": "0"
    },
    {
      "id": 2,
      "name": "죽전휴게소 (서울방향)",
      "image": "https://me2.kr/6cjk8",
      "url": "https://goo.gl/maps/g9vbCSXQHKxAUMWb8",
      "address": "경기 용인시 수지구 경부고속도로 400 (죽전동 866-2번지)",
      "number": "031-262-3168",
      "menu": "죽전임금갈비탕",
      "menu_image": "https://me2.kr/wdrut",
      "price": "10,000",
      "score": "3.7 ★★★★☆",
      "lat": "37.33235675",
      "lng": "127.1047985",
      "menu_info": "죽전 임금 갈비탕! 씹는 식감이 일품인 갈비가 아주 넉넉하게 들어가 있으며 직접 맛을 보면 입에 착착 감기는 깊은 맛과 믿기지 않을 정도로 부드러운 육질에 놀라실 겁니다!!",
      "like": "0"
    },
     {
      "id": 3,
      "name": "망향휴게소 (부산방향)",
      "image": "https://me2.kr/sxx3e",
      "url": "https://goo.gl/maps/RAhdNbLNnV9no7SXA",
      "address": "충남 천안시 서북구 성거읍 돌다리길 23-37",
      "number": "041-557-4000",
      "menu": "명품닭개장",
      "menu_image": "https://me2.kr/hi53b",
      "price": "9,500",
      "score": "3.7 ★★★★☆",
      "lat": "36.85537669",
      "lng": "127.1808716",
      "menu_info": "한국 도로공사 선정 대표 명품음식 명품 닭개장! 얼큰한 육수와 쫄깃한 닭에 조화로 입안에 넣는 순간 퍼지는 진한 맛 괜히 이영자가 먹은 게 아니다!",
      "like": "0"
    },
     {
      "id": 4,
      "name": "옥산휴게소 (부산방향)",
      "image": "https://me2.kr/depor",
      "url": "https://goo.gl/maps/Go1XjzaqC96Dqx1Z7",
      "address": "충북 청주시 흥덕구 옥산면 경부고속도로 309",
      "number": "063-260-1053",
      "menu": "순두부청국장",
      "menu_image": "https://me2.kr/tsfrd",
      "price": "7,000",
      "score": "3.7 ★★★★☆",
      "lat": "36.65771392",
      "lng": "127.36982",
      "menu_info": "직접 만든 순두부로 맛과 영양을 잡았다! 옥산 순두부 청국장 냄새도 심하지 않고 간도 세지 않아 먹기 좋다 심지어 속도 편해 안 먹을 수가 없다!",
      "like": "0"
    },
     {
      "id": 5,
      "name": "죽암휴게소 (부산방향)",
      "image": "https://me2.kr/2vrae",
      "url": "https://goo.gl/maps/BjJMumBpZ3ozMeVS8",
      "address": "충북 청주시 서원구 현도면 경부고속도로 289",
      "number": "043-269-4434",
      "menu": "보은대추왕갈비탕",
      "menu_image": "https://me2.kr/gmukk",
      "price": "11,000",
      "score": "3.7 ★★★★☆",
      "lat": "36.4867809",
      "lng": "127.4292609",
      "menu_info": "천혜의 충북 보은대추와 프리미업 A급 송아지 왕갈비의 부드럽고 진한 명품 갈비탕 보은대추 왕갈비탕 너무너무 맛있다!",
      "like": "0"
    },
    {
      "id": 6,
      "name": "인삼랜드휴게소 (하남방향)",
      "image": "https://me2.kr/t8bit",
      "url": "https://goo.gl/maps/DR2n4x3mBuiRKgDp6",
      "address": "충남 금산군 군북면 대암길 34-30",
      "number": "041-754-5180",
      "menu": "인삼갈비탕",
      "menu_image": "https://me2.kr/2hrfr",
      "price": "10,000",
      "score": "3.8 ★★★★☆",
      "lat": "36.15470489",
      "lng": "127.4976919",
      "menu_info": "대중들이 선호하는 갈비탕에 인삼을 넣은 보양식 인삼갈비탕 인삼향 듬뿍 나는 국물은 내 몸에 건강을 보충해준다!",
      "like": "0"
    },
     {
      "id": 7,
      "name": "이서휴게소 (논산방향)",
      "image": "https://me2.kr/aorw1",
      "url": "https://goo.gl/maps/aZk6eu6DajBHEnEx8",
      "address": "전북 완주군 이서면 호남고속도로 162",
      "number": "063-236-2592",
      "menu": "명품애호박국밥",
      "menu_image": "https://me2.kr/1avqo",
      "price": "8,500",
      "score": "3.8 ★★★★☆",
      "lat": "35.80195263",
      "lng": "127.0257685",
      "menu_info": "건강에 좋은 전라북도 명품 애호박을 푸짐하게 넣고, 국내산 돼지고기와 표고버섯을 추가해 감칠맛을 더한 남도식 돼지국밥!",
      "like": "0"
    },
   {
      "id": 8,
      "name": "정읍녹두장군휴게소(논산방향)",
      "image": "https://me2.kr/vhecd",
      "url": "https://goo.gl/maps/ASsyyGRXr7GwNXxbA",
      "address": "전북 정읍시 북면 하북1길 227-17",
      "number": "063-532-2373",
      "menu": "웰빙 우렁이 쌈밥정식",
      "menu_image": "https://me2.kr/g6nhf",
      "price": "9,000",
      "score": "3.7 ★★★★☆",
      "lat": "35.59996751",
      "lng": "126.8643325",
      "menu_info": "노화방지, 스태미나 증진!! 청정지역에서 길러낸 우렁이를 이용한 웰빙 건강식 웰빙 우렁이 쌈밥정식",
      "like": "0"
    },
    {
      "id": 9,
      "name": "보성녹차휴게소 (순천방향)",
      "image": "https://me2.kr/c6b2a",
      "url": "https://goo.gl/maps/NMKXaMfcqz6dYAFL8",
      "address": "전남 보성군 겸백면 남해고속도로 70",
      "number": "070-4325-8808",
      "menu": "보성꼬막비빔밥",
      "menu_image": "https://me2.kr/mjjzj",
      "price": "10,000",
      "score": "3.8 ★★★★☆",
      "lat": "34.80732155",
      "lng": "127.1809938",
      "menu_info": "대체 불가 꼬막계의 왕중왕 별교 꼬막 넣었다! 새싹 양배추 등 싱싱한 채소들의 환상 궁합 보성 꼬막비빔밥!!",
      "like": "0"
    },
     {
      "id": 10,
      "name": "횡성휴게소 (강릉방향)",
      "image": "https://me2.kr/jja35",
      "url": "https://goo.gl/maps/hYA8ixAWsqTmywKf6",
      "address": "강원 횡성군 안흥면 영동고속도로 154-1",
      "number": "033-342-4231",
      "menu": "한우떡더덕스테이크",
      "menu_image": "https://me2.kr/pm2iq",
      "price": "10,000",
      "score": "3.8 ★★★★☆",
      "lat": "37.46275756",
      "lng": "128.1339693",
      "menu_info": "더덕의 향과 소고기의 향이 어우러져 잘게 썰려 입안에 넣었을때 샤르르 녹는 힝성한우로 빚어낸 환상적인 콜라보레이션",
      "like": 0
    },
    {
      "id": 11,
      "name": "천등산휴게소 (평택방향)",
      "image": "https://me2.kr/br33q",
      "url": "https://goo.gl/maps/Jh5j4Bm8kAjs4qwC7",
      "address": "충북 충주시 산척면 평택제천고속도로 109",
      "number": "043-844-2930",
      "menu": "산삼배왕근을 품은 삼계탕",
      "menu_image": "https://me2.kr/vmnlw",
      "price": "12,000",
      "score": "3.7 ★★★★☆",
      "lat": "37.07694893",
      "lng": "127.9893194",
      "menu_info": "삼계탕을 푸우욱~ 종산삼 dat와 99% 동일한 겨울이 오기전에 먹어야 할 산삼배양푼을 다~~~~ 할머니 마음으로 가득 담은 고봉밥",
      "like": 0
    },
    {
      "id": 12,
      "name": "충주휴게소 (양평방향)",
      "image": "https://me2.kr/huo6w",
      "url": "https://goo.gl/maps/ihuUSL16jt8j2pic8",
      "address": "충북 충주시 중앙탑면 중부내륙고속도로 230",
      "number": "043-857-9229",
      "menu": "한방 고추장 불고기",
      "menu_image": "https://me2.kr/5zosy",
      "price": "12,000",
      "score": "3.7 ★★★★☆",
      "lat": "37.02316775",
      "lng": "127.8392868",
      "menu_info": "국내산 돼지고기를 청주사과와 한방 재료를 첨가한 고추장 앙념으로 요리하여 연육작용, 누린내 제거와 향을 살린 음식",
      "like": 0
    },
     {
      "id": 13,
      "name": "괴산휴게소 (양평방향)",
      "image": "https://me2.kr/21sxz",
      "url": "https://goo.gl/maps/jS2xqxRci5ZoYGEL9",
      "address": "충북 괴산군 장연면 중부내륙고속도로 204",
      "number": "043-832-6594",
      "menu": "엄나무 닭곰탕",
      "menu_image": "https://me2.kr/45w2s",
      "price": "6,000",
      "score": "3.7 ★★★★☆",
      "lat": "36.83177713",
      "lng": "127.9601544",
      "menu_info": "신선한 닭과 엄나루를 푹 고아서 만들어 자극적이지 않은 진하고 단백한 육수가 일품인 건강식 엄나무 닭곰탕!",
      "like": 0
    },
    {
      "id": 14,
      "name": "군위휴게소 (춘천방향)",
      "image": "https://me2.kr/4my7y",
      "url": "https://goo.gl/maps/FkLAvRQM7nxiXzVN7",
      "address": "경북 군위군 군위읍 경북대로 4082",
      "number": "054-383-7114",
      "menu": "제비원된장찌개",
      "menu_image": "https://me2.kr/vih4q",
      "price": "8,000",
      "score": "3.7 ★★★★☆",
      "lat": "36.26549441",
      "lng": "128.5768662",
      "menu_info": "안동 제비원 식품'의 식품명인의 메주 기술제휴를 받아 휴게소에서 직접 담근 된장으로 정성껏 끓인 제비원 된장찌게",
      "like": 0
    },
   {
      "id": 15,
      "name": "추풍령휴게소 (서울방향)",
      "image": "https://me2.kr/5uiqj",
      "url": "https://goo.gl/maps/VAVC1CDFPrGT38pz5",
      "address": "경북 김천시 봉산면 경부고속도로 214-1",
      "number": "054-439-3187",
      "menu": "지례흑돼지석쇠불고기",
      "menu_image": "https://me2.kr/ti0xq",
      "price": "10,000",
      "score": "3.6 ★★★★☆",
      "lat": "36.19971559",
      "lng": "128.0032607",
      "menu_info": "지역에서 생산되는 양질의 토종 흑돼지를 갖은 양념에 재워 즉석에서 숯불로 구은 돼지불고기와 된짱찌게가 나오는 조합",
      "like": 0
    },
     {
      "id": 16,
      "name": "영산휴게소 (마산방향)",
      "image": "https://me2.kr/n0oy1",
      "url": "https://goo.gl/maps/ond4tqD1b9bfbmcKA",
      "address": "경남 창녕군 영산면 신제리 1754-4",
      "number": "055-521-2978",
      "menu": "창녕 양파제육덮밥정식",
      "menu_image": "https://me2.kr/huqc1",
      "price": "9,000",
      "score": "3.6 ★★★★☆",
      "lat": "35.42978632",
      "lng": "128.4958975",
      "menu_info": "맛도 일품! 향도 일품! 창녕앙파의 품미가 가득한 창년양파제육덮밥 정식",
      "like": 0
    },
     {
      "id": 17,
      "name": "경주휴게소 (부산방향)",
      "image": "https://me2.kr/1m59z",
      "url": "https://goo.gl/maps/FEdR3KUsDX3F9yRF9",
      "address": "경북 경주시 내남면 경부고속도로 59",
      "number": "054-748-3195",
      "menu": "동태탕",
      "menu_image": "https://me2.kr/gyx65",
      "price": "8,000",
      "score": "3.7 ★★★★☆",
      "lat": "35.72406922",
      "lng": "129.1926547",
      "menu_info": "주 산내지역 특산물인 산내미나리를 첨가해 시원한 국물 맛을 증가시키고 피로회복 및 다이어트 식품으로도 각광을 받고 있는 속까지 시원한 동태탕",
      "like": 0
    },
     {
      "id": 18,
      "name": "진주휴게소 (부산방향)",
      "image": "https://me2.kr/g5ybv",
      "url": "https://goo.gl/maps/KTf668wiuXiEemjU9",
      "address": "경남 진주시 남해고속도로 194",
      "number": "055-759-3205",
      "menu": "진주 육전 비빔밥",
      "menu_image": "https://me2.kr/w56vd",
      "price": "9,000",
      "score": "3.7 ★★★★☆",
      "lat": "35.15973758",
      "lng": "128.1219843",
      "menu_info": "진주 향토읍식인 담백한 육전과 신선한 채소 식감이 어울러진 영양만점 든든한 프리미엄 비빔밥",
      "like": 0
    },
    {
      "id": 19,
      "name": "섬진강휴게소 (부산방향)",
      "image": "https://me2.kr/wt46i",
      "url": "https://goo.gl/maps/FyZ7uUzqLEjQCSNM6",
      "address": "전남 광양시 진월면 섬진강매화로 141",
      "number": "061-772-7986",
      "menu": "옛날 김치찌개",
      "menu_image": "https://me2.kr/lrl2s",
      "price": "8,000",
      "score": "3.8 ★★★★☆",
      "lat": "34.98468293",
      "lng": "127.7703509",
      "menu_info": "휴게소에서 즐기는 즉석 김치찌개! 시큼 매콤한 김치찌개 국물에 담백한 돼지고기로 화룡점정을 찍은 휴게소 최고의 식사!",
      "like": 0
    },
     {
      "id": 20,
      "name": "기흥휴게소 (부산방향)",
      "image": "https://me2.kr/j84tq",
      "url": "https://goo.gl/maps/WMBh7dMhiPrrLM4f7",
      "address": "경기 용인시 기흥구 공세로 173",
      "number": "031-286-5001",
      "menu": "소고기국밥",
      "menu_image": "https://me2.kr/tbwoa",
      "price": "8,500",
      "score": "3.7 ★★★★☆",
      "lat": "37.23493644",
      "lng": "127.1045459",
      "menu_info": "휴게소 국밥 로드 BEST 5! 깊은 맛의 육수에 밥 한 그릇 말아 먹는 든든한 국민음식",
      "like": 0
    },
    {
      "id": 21,
      "name": "안성휴게소 (부산방향)",
      "image": "https://me2.kr/ps56i",
      "url": "https://goo.gl/maps/aNN3774if5T2Bh6p9",
      "address": "경기 안성시 원곡면 경부고속도로 365",
      "number": "031-655-0531",
      "menu": "안성국밥",
      "menu_image": "https://me2.kr/kb6bc",
      "price": "8,500",
      "score": "3.7 ★★★★☆",
      "lat": "37.01341974",
      "lng": "127.1448075",
      "menu_info": "긴 운전 길 든든하게 먹을 수 있는 안성국밥! 실하게 들어있는 맛 좋은 고기와 얼큰한 국물의 조화를 느껴보자!",
      "like": 0
    },
     {
      "id": 22,
      "name": "여주휴게소 (인천방향)",
      "image": "https://me2.kr/n1zs9",
      "url": "https://goo.gl/maps/oMGKrmm3UxMTPNEr6",
      "address": "경기 여주시 가남읍 화평길 116",
      "number": "031-882-2900",
      "menu": "매운돼지갈비찜",
      "menu_image": "https://me2.kr/drqp5",
      "price": "9,000",
      "score": "3.7 ★★★★☆",
      "lat": "37.23974757",
      "lng": "127.5699538",
      "menu_info": "이영자가 추천한 매운 돼지갈비찜 맛집! 두툼한 돼지고기에 넓적당면과 떡을 넣어 더욱 취향 저격!",
      "like": 0
    },
     {
      "id": 23,
      "name": "문경휴게소 (창원방향)",
      "image": "https://me2.kr/7cpp2",
      "url": "https://goo.gl/maps/LprB8L4jnu9Fb4Us6",
      "address": "경북 문경시 중부내륙고속도로 173",
      "number": "054-554-1655",
      "menu": "전복왕갈비탕",
      "menu_image": "https://me2.kr/w7pnf",
      "price": "12,000",
      "score": "3.8 ★★★★☆",
      "lat": "36.62035937",
      "lng": "128.1499245",
      "menu_info": "장거리 운전으로 지친 운전자에게 딱! 가득한 왕갈비에 전복, 낙지, 대추, 버섯 등 기력 충전 맞춤형 음식!",
      "like": 0
    },
     {
      "id": 24,
      "name": "속리산휴게소 (청주방향)",
      "image": "https://me2.kr/w2dmn",
      "url": "https://goo.gl/maps/NUczRynXhDs2qkpp6",
      "address": "충북 보은군 마로면 적암길 56-18",
      "number": "043-544-1466",
      "menu": "보은대추영양솥밥",
      "menu_image": "https://me2.kr/q0nij",
      "price": "11,000",
      "score": "3.8 ★★★★☆",
      "lat": "36.44769458",
      "lng": "127.8690559",
      "menu_info": "각종 보양 음식을 넣어 향긋하게 지어낸 영양밥의 정석! 영양만점 보양식을 휴게소에서 즐겨보자!",
      "like": 0
    },
     {
      "id": 25,
      "name": "오창휴게소 (통영방향)",
      "image": "https://me2.kr/qqrnk",
      "url": "https://goo.gl/maps/ovXgAQKnhTo6Y4ys5",
      "address": "충북 청주시 청원구 오창읍 중부고속도로 21",
      "number": "043-217-1477",
      "menu": "능이버섯인삼설렁탕",
      "menu_image": "https://me2.kr/as8l1",
      "price": "10,000",
      "score": "3.6 ★★★★☆",
      "lat": "36.75846247",
      "lng": "127.4817963",
      "menu_info": "몸에 좋은 건 모두 모아 뜨끈한 사골 국물 속으로! 여행도 하고 몸보신도 하고 두 마리 토끼를 전부 잡아보자!",
      "like": 0
    },
     {
      "id": 26,
      "name": "천안삼거리휴게소(서울방향)",
      "image": "https://me2.kr/zc0ap",
      "url": "https://goo.gl/maps/bkZ35Xa86y9BtBkD7",
      "address": "충남 천안시 동남구 쉼1길 42",
      "number": "041-551-2480",
      "menu": "해주비빔밥",
      "menu_image": "https://me2.kr/n4psd",
      "price": "10,000",
      "score": "3.7 ★★★★☆",
      "lat": "36.78781395",
      "lng": "127.1734367",
      "menu_info": "황해도의 대표 음식 해주 비빔밥! 아름다운 색감의 다양한 나물로 눈으로 한 번 입으로 한 번 오감으로 즐길 수 있다!",
      "like": 0
    },
    {
      "id": 27,
      "name": "황간휴게소(부산방향)",
      "image": "https://me2.kr/bc6i1",
      "url": "https://goo.gl/maps/1FXeHXUNPeabUEVS6",
      "address": "충북 영동군 황간면 회포길 102",
      "number": "043-742-5805",
      "menu": "영표국밥",
      "menu_image": "https://me2.kr/5wa5f",
      "price": "6,000",
      "score": "3.6 ★★★★☆",
      "lat": "36.24887452",
      "lng": "127.8526489",
      "menu_info": "향긋한 영동 표고버섯 향과 푸짐한 건더기로 속을 든든하게! 국밥 속 영동 표고버섯 향을 느껴보세요!",
      "like": 0
    },
     {
      "id": 28,
      "name": "진안마이산휴게소 (익산방향)",
      "image": "https://me2.kr/vt0yq",
      "url": "https://goo.gl/maps/ZpmFvHsW41Gib28P7",
      "address": "전북 진안군 진안읍 익산장수고속도로 41",
      "number": "063-432-1380",
      "menu": "마이산더덕비빔밥",
      "menu_image": "https://me2.kr/ay8fb",
      "price": "9,000",
      "score": "3.8 ★★★★☆",
      "lat": "35.7778836",
      "lng": "127.4252837",
      "menu_info": "씹을 때 아삭아삭한 식감과 은은한 향기가 매력적인 진안지역 특산품인 더덕을 활용한 건강 비빔밥!",
      "like": 0
    },
     {
      "id": 29,
      "name": "황전휴게소 (전주방향)",
      "image": "https://me2.kr/fc2l1",
      "url": "https://goo.gl/maps/Zekdz7dJ6c7PTBDL9",
      "address": "전남 순천시 황전면 순천완주고속도로 28",
      "number": "061-782-1154",
      "menu": "황전해초꼬막비빔밥",
      "menu_image": "https://me2.kr/yjscy",
      "price": "10,000",
      "score": "3.8 ★★★★☆",
      "lat": "35.15323785",
      "lng": "127.4544854",
      "menu_info": "한 입 크게 떠서 입안에 넣는 순간 상큼한 해초향이 확 나는 식욕 충전 비빔밥!",
      "like": 0
    },
     {
      "id": 30,
      "name": "백양사휴게소 (천안방향)",
      "image": "https://me2.kr/th9ec",
      "url": "https://goo.gl/maps/Gf2F95n8nMjPauXQ7",
      "address": "전남 장성군 북일면 호남고속도로 108",
      "number": "061-394-5177",
      "menu": "삼채애호박찌개",
      "menu_image": "https://me2.kr/34hgt",
      "price": "7,500",
      "score": "3.7 ★★★★☆",
      "lat": "35.39296566",
      "lng": "126.8073964",
      "menu_info": "인삼 뿌리와 애호박 돼지고기까지! 시원하게 속을 뻥 뚫어주는 매콤 칼칼한 애호박 찌개!",
      "like": 0
    },
    {
      "id": 31,
      "name": "칠곡휴게소(서울방향)",
      "image": "https://me2.kr/b4csv",
      "url": "https://goo.gl/maps/D3Bd1kvwGnbQBiUg7",
      "address": "경북 칠곡군 왜관읍 경부고속도로 158 (아곡리 138번지)",
      "number": "054-975-1883",
      "menu": "칠곡벌꿀소머리곰탕",
      "menu_image": "https://me2.kr/b0zv1",
      "price": "9,000",
      "score": "3.8 ★★★★☆",
      "lat": "36.0117912",
      "lng": "128.4308485",
      "menu_info": "소의 머리고기를 여러번 우려내어 깊은 맛을 느낄 수 있는 곰탕에 칠곡 특산품 벌꿀까지! 곰탕계의 혁명이다!",
      "like": 0
    },
     {
      "id": 32,
      "name": "성주휴게소(양평방향)",
      "image": "https://me2.kr/ju1a2",
      "url": "https://goo.gl/maps/by82NGS9SdzbfKs59",
      "address": "경북 성주군 초전면 중부내륙고속도로 98",
      "number": "054-933-0800",
      "menu": "고추장제육볶음",
      "menu_image": "https://me2.kr/qsi4u",
      "price": "8,500",
      "score": "3.8 ★★★★☆",
      "lat": "36.00858484",
      "lng": "128.2611142",
      "menu_info": "집밥의 표본 제육볶음! 이제는 휴게소에서도 맛볼 수 있다?",
      "like": 0
    },
     {
      "id": 33,
      "name": "안동휴게소 (부산방향)",
      "image": "https://me2.kr/r31rk",
      "url": "https://goo.gl/maps/FZGYpcAnAvBNNodAA",
      "address": "경북 안동시 풍산읍 풍산태사로 1903-27",
      "number": "054-853-4370",
      "menu": "이동삼안동간고등어정식",
      "menu_image": "https://me2.kr/z8lz7",
      "price": "10,000",
      "score": "3.7 ★★★★☆",
      "lat": "36.55317367",
      "lng": "128.6419077",
      "menu_info": "대한민국 밥도둑 하나 더 추가요! 한입 뜯어 먹으면 잊을 수 없는 짭짤 단백한 고등어 구이!",
      "like": 0
    },
    {
      "id": 34,
      "name": "진영휴게소 (순천방향)",
      "image": "https://me2.kr/13tpu",
      "url": "https://goo.gl/maps/GbbEjRyRSatRrdDK7",
      "address": "경남 김해시 진영읍 하계로96번길 68",
      "number": "055-342-3959",
      "menu": "장군차생고기김치찌개",
      "menu_image": "https://me2.kr/uyp1a",
      "price": "7,500",
      "score": "3.7 ★★★★☆",
      "lat": "35.28007441",
      "lng": "128.7160108",
      "menu_info": "김해 지역 특산품 장군차를 푹 끓인 물에 김치찌개를 끓였다! 돼지의 잡내가 전혀 없는 얼큰한 김치찌개!",
      "like": 0
    },
    {
      "id": 35,
      "name": "산청휴게소 (하남방향)",
      "image": "https://me2.kr/7m39q",
      "url": "https://goo.gl/maps/AS5EYgNoFDcoog3T9",
      "address": "경남 산청군 단성면 통영대전고속도로 76",
      "number": "055-973-1703",
      "menu": "한방우불고기",
      "menu_image": "https://me2.kr/uhoc0",
      "price": "9,000",
      "score": "3.8 ★★★★☆",
      "lat": "35.33349892",
      "lng": "127.9389968",
      "menu_info": "인삼, 당귀, 대추를 아낌없이 넣어 정성스럽게 만들어진 한방우불고기! 한 입 먹는 순간 휴게소에서 맛볼 수 없는 깊고 진한 맛이 펼쳐진다!",
      "like": 0
    },
     {
      "id": 36,
      "name": "통도사휴게소 (부산방향)",
      "image": "https://me2.kr/qzkpp",
      "url": "https://goo.gl/maps/PwaPhQXQZ5CbDxd2A",
      "address": "경남 양산시 하북면 경부고속도로 31-1",
      "number": "055-383-6145",
      "menu": "명품낙지덮밥",
      "menu_image": "https://me2.kr/wwl7r",
      "price": "9,500",
      "score": "3.8 ★★★★☆",
      "lat": "35.4888535",
      "lng": "129.090756",
      "menu_info": "조방낙지에서 착안한 15가지 재료를 듬뿍 넣어 양념장을 만든 낙지볶음과 따뜻한 흰 쌀밥의 조화!",
      "like": 0
    }




]
db.lats1.insert_many(doc)